{
 "title": "FairyringClient Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Last Processed Height",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fairyringclient_latest_processed_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Valid Key Share Submitted",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fairyringclient_valid_share_submitted",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Key Share Expires in...",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fairyringclient_current_share_expiry-fairyringclient_latest_processed_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Key Share Submitted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fairyringclient_invalid_share_submitted",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Key Shares Failed To Submit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fairyringclient_failed_share_submitted",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}